service: altu-chatgpt

frameworkVersion: '3'

provider:
  name: aws
  endpointType: REGIONAL
  stage: ${opt:stage, 'local'}
  runtime: nodejs16.x
  region: sa-east-1
    
  versionFunctions: false
  timeout: 30
  memorySize: 128  

functions:
  - ${file(./services/config.yml):functions}

custom:
  customDomain: ${file(./services/config.yml):customDomain}
  serverless-offline:
    host: 127.0.0.1
    port: 3000
    noPrependStageInUrl: true
  binary:
    types:
      - '*/*' # permitir o tipo de conteúdo de qualquer payload
    maxSize: 10 # definir o tamanho máximo da carga útil em MB

plugins:
  - serverless-offline
  - serverless-plugin-optimize
  - serverless-domain-manager
  - serverless-plugin-typescript
