functions:
  cognitiveSearch:
    handler: services/cognitive-search/index.handler
    events:
      - http:
          path: services/cognitive-search
          method: GET
          cors: true
  openai:
    handler: services/conversation-openai/index.handler
    events:
      - http:
          path: services/conversation-openai
          method: POST
          cors: true
